# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-20 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=120)),
                ('last', models.CharField(max_length=120)),
                ('emailid', models.EmailField(max_length=260)),
            ],
        ),
    ]
